### ISSUE TITLE
同一时间点写入的多条数据到日志服务，但消费者同一时间只能消费一条数据

### ISSUE THREAD

**Issue by breakstones** [aliyun/aliyun-log-flink-connector#7]
配置如下：
> configProps.put(ConfigConstants.LOG_CONSUMERGROUP, "write_to_es");
configProps.put(ConfigConstants.LOG_CONSUMER_BEGIN_POSITION, Consts.LOG_END_CURSOR);
configProps.put(ConfigConstants.LOG_FETCH_DATA_INTERVAL_MILLIS, "100");
configProps.put(ConfigConstants.LOG_MAX_NUMBER_PER_FETCH, "1000");
RawLogGroupListDeserializer deserializer = new RawLogGroupListDeserializer();
final StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
env.getCheckpointConfig().setCheckpointingMode(CheckpointingMode.EXACTLY_ONCE);
env.enableCheckpointing(5000);
DataStream<RawLogGroupList> logTestStream = env.addSource(
        new FlinkLogConsumer<>(deserializer, configProps));
logTestStream.addSink(new ProcessLog());
env.execute();

**Comment by liketic** [comment]
> 消费者同一时间只能消费一条数据
是指什么意思？每个shard都有一个consumer group线程消费。

**Comment by breakstones** [comment]
只有一个shard，是说读取数据有问题

日志服务里面的数据如下：
> time                     log
 2018-8-1 14:04:43  log_1
 2018-8-1 14:04:43  log_2
 2018-8-1 14:04:43  log_3
 2018-8-1 14:04:44  log_4
 2018-8-1 14:04:44  log_5
 2018-8-1 14:04:44  log_6

FlinkLogConsumer 能读取到的数据只有：
> time                    log
 2018-8-1 14:04:43  log_1
 2018-8-1 14:04:44  log_4

**Comment by breakstones** [comment]
已查明是使用方式有问题
